### ISSUE TITLE
invalid high s-value encountered in r1 signature at /v1/chain/send_transaction2

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2056]
Hi

Once in a ~10 transaction, I am getting the following error:
`
"message": "invalid high s-value encountered in r1 signature at /v1/chain/send_transaction2",
"stack": "exception: invalid high s-value encountered in r1 signature at /v1/chain/send_transaction2\n    at APIClient.<anonymous> (/Users/dev-dante/Documents/Codes/eos/node_modules/@wharfkit/antelope/src/api/client.ts:139:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/dev-dante/Documents/Codes/eos/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
      }
    }
`

I looked through the code base but couldn't figure out what's the reason. The error is coming from this [line](https://github.com/AntelopeIO/leap/blob/ecbcf94bf7223d0fa87fd7ef7a88a1d778855bd2/libraries/libfc/src/crypto/elliptic_r1.cpp#L536).

PS:
I am using `wharfkit/antelope` library to send transaction.
My accounts public/private key is `R1`, not `K1`.

**Comment by bhazzard** [comment]
@dev-dantealighieri Are you using a custom signature provider implementation?

@aaroncox does this ring any bells for you?

**Comment by spoonincode** [comment]
You need to make sure the signature is in canonical format which for secp256r1 signatures in leap means the s value is less than the half order of the curve. If you're using `elliptic` it can do that for you by passing `canonical: true`. For example, how wharfkit passes that option when performing the signatur with `elliptic`,
https://github.com/wharfkit/antelope/blob/master/src/crypto/sign.ts#L22

**Comment by spoonincode** [comment]
Closing due to inactivity for over a month, if you need more help on this topic feel free to reply
