### ISSUE TITLE
Test Failure: nodeos_extra_packed_data_test.py

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#380]
https://github.com/AntelopeIO/leap/actions/runs/3317534588/jobs/5480550909

```
Traceback (most recent call last):
  File "/__w/leap/leap/build/tests/nodeos_extra_packed_data_test.py", line 168, in <module>
    trx_id = sentTrx["transaction_id"]
KeyError: 'transaction_id'
```

**Comment by heifner** [comment]
Another: https://github.com/AntelopeIO/leap/actions/runs/3351951287/jobs/5553772250

```
Traceback (most recent call last):
  File "/__w/leap/leap/build/tests/nodeos_extra_packed_data_test.py", line 168, in <module>
    trx_id = sentTrx["transaction_id"]
KeyError: 'transaction_id'
```
